### Start Ventilator
POST {{host}}/api/ventilator/start
Accept: application/json

###

### Stop Ventilator
POST {{host}}/api/ventilator/stop
Accept: application/json

###

### Set Ventilator Speed
PUT {{host}}/api/ventilator/speed/3
Accept: application/json

### Set Ventilator Speed
POST {{host}}/api/ventilator/rotate
Accept: application/json

### Get the state
GET {{host}}/api/ventilator/state
Accept: application/json