### Start Ventilator
POST {{host}}/api/v1/ventilator/start
Accept: application/json

###

### Stop Ventilator
POST {{host}}/api/v1/ventilator/stop
Accept: application/json

###

### Set Ventilator Speed
PUT {{host}}/api/v1/ventilator/speed/3
Accept: application/json

### Rotate Ventilator
POST {{host}}/api/v1/ventilator/rotate
Accept: application/json

### Get the state
GET {{host}}/api/v1/ventilator/state
Accept: application/json
